import { StyleSheet } from 'react-native';
import { COLORS, FONT, SIZES } from '../constants';

const styles = StyleSheet.create({
  headerTitle: {
    fontSize: SIZES.xLarge,
    fontWeight: 'bold',
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: SIZES.large,
    letterSpacing: 1.5,
    textShadowColor: COLORS.black,
    textShadowOffset: { width: 10, height: 3 },
    textShadowRadius: 20,
  },
  scrollViewContent: {
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  introContainer: {
    alignItems: 'center',
    marginBottom: SIZES.large,
    backgroundColor: COLORS.lightWhite,
    padding: SIZES.large,
    borderRadius: SIZES.xLarge,
    elevation: 10,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
  },
  introImage: {
    width: '100%',
    height: 200,
    borderRadius: SIZES.medium,
    marginBottom: SIZES.medium,
  },
  introText: {
    fontSize: SIZES.medium,
    fontFamily: FONT.regular,
    color: COLORS.darkGreen,
    textAlign: 'center',
    lineHeight: 26,
    marginBottom: SIZES.medium,
    textShadowColor: COLORS.white,
    textShadowOffset: { width: 1, height: 1.5 },
    textShadowRadius: 4,
  },
  highlightContainer: {
    backgroundColor: COLORS.primary,
    padding: SIZES.medium,
    borderRadius: SIZES.medium,
    marginTop: SIZES.small,
    elevation: 5,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
  },
  highlightTitle: {
    fontSize: SIZES.large,
    fontFamily: FONT.bold,
    color: COLORS.white,
    textAlign: 'center',
    marginBottom: SIZES.small,
  },
  highlightText: {
    fontSize: SIZES.medium,
    fontFamily: FONT.medium,
    color: COLORS.lightWhite,
    textAlign: 'center',
    lineHeight: 24,
  },
  searchTitle: {
    fontFamily: FONT.bold,
    fontSize: SIZES.xxLarge,
    color: COLORS.tertiary,
    marginBottom: SIZES.medium,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.75)',
    textShadowOffset: { width: 2, height: 2 },
    textShadowRadius: 15,
  },
  animalCard: {
    backgroundColor: COLORS.forestGreen,
    borderRadius: SIZES.large,
    padding: SIZES.medium,
    marginBottom: SIZES.large,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 20,
    alignItems: 'center',
    width: 270,
    marginHorizontal: SIZES.medium,
  },
  animalImage: {
    width: '100%',
    height: 200,
    borderRadius: SIZES.large,
    marginBottom: SIZES.small,
  },
  animalName: {
    fontSize: SIZES.xLarge,
    fontFamily: FONT.bold,
    color: COLORS.lightWhite,
    textAlign: 'center',
    marginBottom: SIZES.medium,
    textShadowColor: COLORS.black,
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 4,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    paddingHorizontal: SIZES.xLarge,
  },
  modalContent: {
    width: '95%',
    backgroundColor: COLORS.white,
    borderRadius: SIZES.xLarge,
    padding: SIZES.large,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.6,
    shadowRadius: 15,
    elevation: 20,
    alignItems: 'center',
  },
  modalTitle: {
    fontSize: SIZES.xxxLarge,
    fontFamily: FONT.bold,
    color: COLORS.primary,
    marginBottom: SIZES.large,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.85)',
    textShadowOffset: { width: 2, height: 3 },
    textShadowRadius: 15,
  },
  modalImage: {
    width: '100%',
    height: 220,
    borderRadius: SIZES.large,
    marginBottom: SIZES.medium,
  },
  modalInfoContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: SIZES.medium,
  },
  modalInfo: {
    fontSize: SIZES.medium,
    color: COLORS.secondary,
    textAlign: 'center',
    fontFamily: FONT.medium,
    lineHeight: 26,
    marginHorizontal: SIZES.small,
  },
  modalInfoLabel: {
    fontSize: SIZES.medium,
    color: COLORS.primary,
    textAlign: 'center',
    fontFamily: FONT.bold,
    marginBottom: SIZES.small,
  },
  closeButton: {
    marginTop: SIZES.large,
    backgroundColor: COLORS.primary,
    borderRadius: SIZES.large,
    paddingVertical: SIZES.medium,
    paddingHorizontal: SIZES.large,
    elevation: 10,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  closeButtonText: {
    fontSize: SIZES.large,
    color: COLORS.white,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  carouselContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: SIZES.large,
    paddingHorizontal: SIZES.medium,
    justifyContent: 'center',
  },
  arrowIcon: {
    width: 28,
    height: 28,
    tintColor: COLORS.white,
  },
});

export default styles;
