import { StyleSheet } from 'react-native';
import { COLORS, FONT, SIZES } from '../constants';

const styles = StyleSheet.create({
  headerTitle: {
    fontSize: SIZES.xLarge,
    fontWeight: 'bold',
    color: COLORS.white,
    textAlign: 'center',
    marginTop: 0,
    marginBottom: SIZES.large,
    letterSpacing: 1.5,
    textShadowColor: COLORS.black,
    textShadowOffset: { width: 10, height: 3 },
    textShadowRadius: 20,
  },
  scrollViewContent: {
    paddingBottom: 20,
    paddingHorizontal: 20,
  },
  animalCard: {
    backgroundColor: COLORS.forestGreen,
    borderRadius: SIZES.large,
    padding: SIZES.medium,
    marginBottom: SIZES.large,
    shadowColor: COLORS.black,
    shadowOffset: {
      width: 0,
      height: 8,
    },
    shadowOpacity: 0.5,
    shadowRadius: 15,
    elevation: 20,
    alignItems: 'center',
    borderWidth: 0,
    width: 270,
    marginHorizontal: SIZES.medium,
    overflow: 'hidden',
    transform: [{ scale: 1 }],
  },
  animalImage: {
    width: '100%',
    height: 200,
    borderRadius: SIZES.large,
    marginBottom: SIZES.small,
  },
  animalName: {
    fontSize: SIZES.xLarge,
    fontFamily: FONT.bold,
    color: COLORS.lightWhite,
    textAlign: 'center',
    marginBottom: SIZES.medium,
    textShadowColor: COLORS.black,
    textShadowOffset: { width: 5, height: 5 },
    textShadowRadius: 4,
  },
  modalTitle: {
    fontSize: SIZES.xxxLarge,
    fontFamily: FONT.bold,
    color: COLORS.primary,
    marginBottom: SIZES.large,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.85)',
    textShadowOffset: { width: 2, height: 3 },
    textShadowRadius: 15,
  },
  modalImage: {
    width: '100%',
    height: 220,
    borderRadius: SIZES.large,
    marginBottom: SIZES.medium,
  },
  modalInfo: {
    fontSize: SIZES.medium,
    color: COLORS.secondary,
    marginBottom: SIZES.small,
    textAlign: 'center',
    fontFamily: FONT.medium,
    lineHeight: 26,
  },
  closeButton: {
    marginTop: SIZES.large,
    backgroundColor: COLORS.primary,
    borderRadius: SIZES.large,
    paddingVertical: SIZES.medium,
    paddingHorizontal: SIZES.large,
    elevation: 10,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
  },
  closeButtonText: {
    fontSize: SIZES.large,
    color: COLORS.white,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  carouselContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: SIZES.large,
    paddingHorizontal: SIZES.medium,
    justifyContent: 'center',
  },
  arrowIcon: {
    width: 28,
    height: 28,
    tintColor: COLORS.white,
  },
});

export default styles;
