import { StyleSheet } from 'react-native';
import { COLORS, FONT, SIZES } from '../../constants';

const styles = StyleSheet.create({
  backgroundImage: {
    flex: 1,
    resizeMode: 'cover',
  },
  headerTitle: {
    fontSize: SIZES.xLarge,
    fontWeight: 'bold',
    color: COLORS.white,
    textAlign: 'center',
    marginTop: SIZES.xxLarge,
    marginBottom: SIZES.large,
    letterSpacing: 1.5,
    textShadowColor: 'rgba(0, 0, 0, 0.85)',
    textShadowOffset: { width: 3, height: 3 },
    textShadowRadius: 15,
  },
  searchContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: SIZES.large,
    height: 50,
    borderRadius: SIZES.large,
    paddingHorizontal: SIZES.small,
  },
  searchWrapper: {
    flex: 1,
    backgroundColor: COLORS.white,
    marginRight: SIZES.small,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: SIZES.medium,
    height: '100%',
  },
  searchInput: {
    fontFamily: FONT.regular,
    width: '100%',
    height: '100%',
    paddingHorizontal: SIZES.medium,
  },
  searchBtn: {
    width: 50,
    height: '100%',
    backgroundColor: COLORS.tertiary,
    borderRadius: SIZES.medium,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBtnImage: {
    width: '50%',
    height: '50%',
    tintColor: COLORS.white,
  },
  tabsContainer: {
    width: '100%',
    marginTop: SIZES.medium,
  },
  tab: {
    paddingVertical: SIZES.small,
    paddingHorizontal: SIZES.medium,
    borderRadius: SIZES.medium,
    borderWidth: 1,
    borderColor: COLORS.secondary,
    backgroundColor: COLORS.primary,
    marginHorizontal: SIZES.small / 2,
  },
  tabText: {
    fontFamily: FONT.medium,
    color: COLORS.white,
    textAlign: 'center',
  },
  recentSearchesContainer: {
    marginHorizontal: SIZES.medium,
    marginTop: SIZES.medium,
    padding: SIZES.small,
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: SIZES.medium,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  recentSearchesTitle: {
    fontSize: SIZES.medium,
    fontFamily: FONT.bold,
    color: COLORS.primary,
    marginBottom: SIZES.small,
  },
  recentSearchesBox: {
    paddingVertical: SIZES.small,
    backgroundColor: COLORS.lightWhite,
    borderRadius: SIZES.small,
  },
  recentSearchItemContainer: {
    backgroundColor: COLORS.white,
    padding: SIZES.small,
    borderRadius: SIZES.small,
    marginHorizontal: SIZES.small / 2,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 4,
  },
  recentSearchItem: {
    fontSize: SIZES.small,
    color: COLORS.primary,
    fontFamily: FONT.medium,
  },
  introductionContainer: {
    marginTop: SIZES.large,
    paddingHorizontal: SIZES.medium,
    paddingBottom: SIZES.large,
  },
  imageWrapper: {
    alignItems: 'center',
    marginBottom: SIZES.large,
    borderRadius: SIZES.large,
    overflow: 'hidden',
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  animalImage: {
    width: '100%',
    height: 250,
    borderRadius: SIZES.medium,
  },
  infoContainer: {
    paddingHorizontal: SIZES.medium,
    paddingVertical: SIZES.medium,
    backgroundColor: COLORS.lightWhite,
    borderRadius: SIZES.medium,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.2,
    shadowRadius: 15,
    elevation: 10,
  },
  infoCard: {
    marginBottom: SIZES.medium,
    padding: SIZES.large,
    backgroundColor: COLORS.white,
    borderRadius: SIZES.medium,
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  descriptionCard: {
    padding: SIZES.large,
    backgroundColor: COLORS.white,
    borderRadius: SIZES.medium,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
    borderWidth: 1,
    borderColor: COLORS.gray2,
  },
  animalName: {
    fontSize: SIZES.xLarge,
    fontWeight: 'bold',
    color: COLORS.primary,
    textAlign: 'center',
  },
  animalInfo: {
    fontSize: SIZES.medium,
    color: COLORS.secondary,
    textAlign: 'center',
    lineHeight: 22,
  },
  animalDescription: {
    fontSize: SIZES.medium,
    lineHeight: 24,
    color: COLORS.darkGray,
    textAlign: 'justify',
  },
  navigationButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: SIZES.medium,
    paddingHorizontal: SIZES.large,
    borderRadius: SIZES.large,
    alignItems: 'center',
    marginTop: SIZES.medium,
    shadowColor: COLORS.black,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 5,
  },
  navigationButtonText: {
    color: COLORS.white,
    fontSize: SIZES.medium,
    fontFamily: FONT.bold,
  },
});

export default styles;
